### ISSUE TITLE
Set up AWS infrastructure with SAM template

### ISSUE THREAD

**Issue by hnprashanth** [hnprashanth/salesforce-agent#10]
## Task Description
Create complete AWS SAM template for all infrastructure components needed for the application.

## Acceptance Criteria
- [ ] API Gateway configuration with CORS
- [ ] Lambda functions with proper IAM roles
- [ ] DynamoDB tables for sessions and cache
- [ ] Secrets Manager for API keys
- [ ] CloudWatch logs and alarms
- [ ] Environment-specific parameters

### API Gateway
- REST API with proxy integration
- CORS configuration
- API key authentication
- Usage plans and throttling

### Lambda Functions
- Chat handler
- Salesforce auth
- Opportunity data access
- AI integration
- Analysis engine

### DynamoDB Tables
- SessionTable (userId, tokens, expiry)
- CacheTable (key, data, TTL)
- ChatHistoryTable (sessionId, messages)

### Security
- KMS key for encryption
- Secrets Manager for:
  - Salesforce credentials
  - OpenAI/Claude API keys
  - JWT secret
- IAM roles with least privilege

### Monitoring
- CloudWatch dashboards
- Lambda function metrics
- API Gateway metrics
- Error alarms
- Cost tracking

## Template Structure
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
  OpenAIApiKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
```
