### ISSUE TITLE
Set up CI/CD pipeline with GitHub Actions

### ISSUE THREAD

**Issue by hnprashanth** [hnprashanth/salesforce-agent#12]
## Task Description
Create GitHub Actions workflows for automated testing, building, and deployment to AWS.

**UPDATE**: Changed from AWS SAM to AWS CDK as implemented in PR #17.

## Acceptance Criteria
- [ ] CI workflow for pull requests
- [ ] CD workflow for main branch
- [ ] Automated testing (unit and integration)
- [ ] CDK build and deploy (updated from SAM)
- [ ] Frontend build and S3 deployment
- [ ] Environment-specific deployments

## CI Workflow (PR checks)
```yaml
name: CI
on:
  pull_request:
    branches: [main]

jobs:
  test-backend:
    - Lint Lambda functions
    - Run unit tests
    - Check CDK stack validity (updated from SAM)
    - CDK synth to validate templates
    
  test-frontend:
    - Lint React code
    - Run component tests
    - Type checking
    - Build verification
```

## CD Workflow (Deploy)
```yaml
name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy-dev:
    - Build CDK application (updated from SAM)
    - Deploy to dev environment with CDK
    - Run smoke tests
    
  deploy-prod:
    - Manual approval required
    - Deploy to production with CDK
    - Run health checks
```

## CDK-Specific Commands
```bash
# Instead of SAM commands, use:
npm run build          # Compile TypeScript
npm test              # Run tests
npx cdk synth         # Generate CloudFormation
npx cdk deploy        # Deploy stack
npx cdk diff          # Show deployment diff
```

## AWS Credentials
- Use GitHub OIDC provider
- Environment-specific IAM roles
- Least privilege permissions
- CDK bootstrap permissions required

## Frontend Deployment
- Build React app
- Upload to S3
- Invalidate CloudFront cache
- Update API endpoints from CDK outputs

## Monitoring
- Deployment notifications
- Error alerts
- Performance metrics
- CDK deployment status

## Current CDK Infrastructure
✅ **Successfully deployed via CDK**
- API URL: https://dwc1jc6bxd.execute-api.ap-south-1.amazonaws.com/prod/
- Backend deployed in ap-south-1 region
- All endpoints tested and working
